version: 1

AppDir:
  path: AppDir
  app_info:
    id: com.vesvese55x.belgeselsemoflix
    name: BELGESELSEMOFLIX
    icon: belgeselsemoflix
    version: 1.0.0
    exec: usr/bin/belgeselsemoflix
    exec_args: $@
  apt:
    arch: amd64
    allow_unauthenticated: true
    sources:
      - sourceline: deb http://archive.ubuntu.com/ubuntu/ jammy main restricted universe multiverse
      - sourceline: deb http://archive.ubuntu.com/ubuntu/ jammy-updates main restricted universe multiverse
      - sourceline: deb http://security.ubuntu.com/ubuntu/ jammy-security main restricted universe multiverse
    include:
      - ca-certificates
      - libasound2
      - libc6
      - libcairo2
      - libdbus-1-3
      - libdrm2
      - libfontconfig1
      - libfreetype6
      - libgcc-s1
      - libgdk-pixbuf-2.0-0
      - libglib2.0-0
      - libgtk-3-0
      - libharfbuzz0b
      - libnspr4
      - libnss3
      - libpango-1.0-0
      - libpangocairo-1.0-0
      - libsoup-3.0-0
      - libstdc++6
      - libwayland-client0
      - libwayland-cursor0
      - libwayland-egl1
      - libwebkit2gtk-4.1-0
      - libx11-6
      - libxcomposite1
      - libxdamage1
      - libxext6
      - libxfixes3
      - libxkbcommon0
      - libxrandr2
      - zlib1g
  files:
    exclude:
      - usr/include/**
      - usr/lib/systemd/**
      - usr/share/doc/**
      - usr/share/lintian/**
      - usr/share/locale/**
      - usr/share/man/**
  runtime:
    env:
      APPDIR: $APPDIR
      XDG_DATA_DIRS: $APPDIR/usr/share:$XDG_DATA_DIRS

AppImage:
  arch: x86_64
